name: Deploy Develop

defaults:
  run:
    working-directory: ./terraform

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: us-east-2

jobs:
  lint:
    name: Deploy Develop
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.DEVELOP_AWS_ACCOUNT_ID }}:role/CICD-Role
          role-session-name: ci-cd-session
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Init
        run: terraform init -backend-config=develop.backend.config.tfvars

      - name: Validate
        run: terraform validate -no-color

      - name: Check Format
        run: terraform fmt -check

      - name: Build lambdas
        run: make all
        working-directory: ../

      - name: Apply
        run: terraform apply -auto-approve
