name: Lint Terraform

defaults:
  run:
    working-directory: "./terraform"

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

jobs:
  lint:
    name: Lint Terraform
    runs-on: ubuntu-latest
    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Checkout
      uses: actions/checkout@v3

    - name: Validate
      run: terraform validate -no-color

    - name: Check Format
      run: terraform fmt -check
